In [2]:
import torch

In [ ]:
[2,3,4],[3,4,5] = 2 1 3

In [20]:
X = torch.rand(2,1,3)
X


tensor([[[0.1006, 0.3038, 0.2519]],

        [[0.7502, 0.7816, 0.2360]]])

In [22]:
u =X.squeeze()

In [23]:
t = u.squeeze()

In [24]:
t

tensor([[0.1006, 0.3038, 0.2519],
        [0.7502, 0.7816, 0.2360]])

In [5]:
Y = torch.rand(1,9)

In [6]:
Y

tensor([[0.6761, 0.5331, 0.7778, 0.2324, 0.9595, 0.1918, 0.1669, 0.7090, 0.4608]])

In [7]:
z = Y.squeeze()

In [9]:
z

tensor([0.6761, 0.5331, 0.7778, 0.2324, 0.9595, 0.1918, 0.1669, 0.7090, 0.4608])

In [10]:
z.squeeze()

tensor([0.6761, 0.5331, 0.7778, 0.2324, 0.9595, 0.1918, 0.1669, 0.7090, 0.4608])

In [12]:
z.shape

torch.Size([9])

In [15]:
p = z.unsqueeze(dim=0)

In [17]:
q =p.unsqueeze(dim=0)

In [18]:
q.shape

torch.Size([1, 1, 9])

In [25]:
q

tensor([[[0.6761, 0.5331, 0.7778, 0.2324, 0.9595, 0.1918, 0.1669, 0.7090,
          0.4608]]])

In [26]:
w =q.unsqueeze(dim=0)
w

tensor([[[[0.6761, 0.5331, 0.7778, 0.2324, 0.9595, 0.1918, 0.1669, 0.7090,
           0.4608]]]])

In [27]:
w.shape

torch.Size([1, 1, 1, 9])

In [28]:
w.squeeze()

tensor([0.6761, 0.5331, 0.7778, 0.2324, 0.9595, 0.1918, 0.1669, 0.7090, 0.4608])

Permute

In [46]:
 e = torch.rand(224,224,3)
 e.shape

torch.Size([224, 224, 3])

In [45]:
a = e.permute(1,0,2)
a.shape

torch.Size([224, 224, 3])

In [51]:
r = e.permute(2,0,1)
r.shape

torch.Size([3, 224, 224])

In [52]:
q = e.permute(2,1,0)
q.shape

torch.Size([3, 224, 224])

Find the difference between torch.mm vs torch.mul.torch.matmul

In [ ]:
torch.matmul(r,q).shape

In [ ]:
torch.mul(r,q).shape

torch.Size([3, 224, 224])