In [1]:
import torch

In [22]:
x = torch.arange(0,10)

In [30]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
z = x.reshape(2,5)
z
z.shape

torch.Size([2, 5])

In [25]:
y = x
y

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
y = x.view(1,10)

In [40]:
y[:,6] = 4 # :, is the syntex for view
y,x

(tensor([[4, 1, 2, 3, 4, 5, 4, 7, 8, 9]]),
 tensor([4, 1, 2, 3, 4, 5, 4, 7, 8, 9]))

In [52]:
x_stacked = torch.stack([x,x,x,x,x,x,x],dim=1)
x_stacked

tensor([[4, 4, 4, 4, 4, 4, 4],
        [1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5],
        [4, 4, 4, 4, 4, 4, 4],
        [7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9, 9, 9]])

In [50]:
x_stacked =torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[4, 1, 2, 3, 4, 5, 4, 7, 8, 9],
        [4, 1, 2, 3, 4, 5, 4, 7, 8, 9],
        [4, 1, 2, 3, 4, 5, 4, 7, 8, 9],
        [4, 1, 2, 3, 4, 5, 4, 7, 8, 9]])

In [58]:
x_stacked =torch.stack([z,z,z,z],dim=2)
x_stacked

tensor([[[4, 4, 4, 4],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]],

        [[5, 5, 5, 5],
         [4, 4, 4, 4],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]])

In [74]:
t = torch.rand(3,6)


Torch Stack has some confusion!!

In [78]:
y = torch.stack([t,t,t],dim= 1) 
y 

tensor([[[0.9598, 0.7479, 0.0840, 0.0622, 0.9645, 0.7284],
         [0.9598, 0.7479, 0.0840, 0.0622, 0.9645, 0.7284],
         [0.9598, 0.7479, 0.0840, 0.0622, 0.9645, 0.7284]],

        [[0.3802, 0.9113, 0.7283, 0.0756, 0.4530, 0.4343],
         [0.3802, 0.9113, 0.7283, 0.0756, 0.4530, 0.4343],
         [0.3802, 0.9113, 0.7283, 0.0756, 0.4530, 0.4343]],

        [[0.9336, 0.3424, 0.3865, 0.8382, 0.8502, 0.4759],
         [0.9336, 0.3424, 0.3865, 0.8382, 0.8502, 0.4759],
         [0.9336, 0.3424, 0.3865, 0.8382, 0.8502, 0.4759]]])