In [2]:
import torch

In [3]:
x = torch.arange(0,10)

In [4]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
z = x.reshape(2,5)
z
z.shape

torch.Size([2, 5])

In [6]:
y = x
y

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
y = x.view(1,10)

In [8]:
y[:,6] = 4 # :, is the syntex for view
y,x

(tensor([[0, 1, 2, 3, 4, 5, 4, 7, 8, 9]]),
 tensor([0, 1, 2, 3, 4, 5, 4, 7, 8, 9]))

In [9]:
x_stacked = torch.stack([x,x,x,x,x,x,x],dim=1)
x_stacked

tensor([[0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5],
        [4, 4, 4, 4, 4, 4, 4],
        [7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9, 9, 9]])

In [10]:
x_stacked =torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[0, 1, 2, 3, 4, 5, 4, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 4, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 4, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 4, 7, 8, 9]])

In [11]:
x_stacked =torch.stack([z,z,z,z],dim=2)
x_stacked

tensor([[[0, 0, 0, 0],
         [1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4]],

        [[5, 5, 5, 5],
         [4, 4, 4, 4],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]])

In [12]:
t = torch.rand(3,6)


Torch Stack has some confusion!!

In [13]:
y = torch.stack([t,t,t],dim= 1) 
y 

tensor([[[0.2937, 0.3958, 0.5414, 0.4419, 0.7953, 0.3997],
         [0.2937, 0.3958, 0.5414, 0.4419, 0.7953, 0.3997],
         [0.2937, 0.3958, 0.5414, 0.4419, 0.7953, 0.3997]],

        [[0.1348, 0.4531, 0.6535, 0.1437, 0.2298, 0.1435],
         [0.1348, 0.4531, 0.6535, 0.1437, 0.2298, 0.1435],
         [0.1348, 0.4531, 0.6535, 0.1437, 0.2298, 0.1435]],

        [[0.0264, 0.1841, 0.1836, 0.8863, 0.6268, 0.6749],
         [0.0264, 0.1841, 0.1836, 0.8863, 0.6268, 0.6749],
         [0.0264, 0.1841, 0.1836, 0.8863, 0.6268, 0.6749]]])

In [14]:
y.shape

torch.Size([3, 3, 6])

In [15]:
torch.rand(3,3)

tensor([[0.4386, 0.8084, 0.3153],
        [0.7322, 0.8341, 0.6581],
        [0.5951, 0.7998, 0.6064]])