In [1]:
import torch

In [2]:
import numpy as np

In [3]:
%timeit torch.arange(10,100,5)

The slowest run took 11.32 times longer than the fastest. This could mean that an intermediate result is being cached.
41.9 µs ± 30.7 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit np.arange(10,100,5)

835 ns ± 26.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
y = torch.rand(3,3)
y

tensor([[0.1797, 0.1150, 0.7216],
        [0.7399, 0.6804, 0.1942],
        [0.1213, 0.0582, 0.9136]])

In [6]:
y = torch.arange(1,10).reshape(1,3,3)
y

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [7]:
y[0][2][2]

tensor(9)

In [8]:
y[:,2,2]

tensor([9])

In [9]:
y[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [10]:
y[:,:,2]

tensor([[3, 6, 9]])

In [11]:
o = np.arange(1,10)
p = torch.from_numpy(o)
print(p,p.device)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32) cpu


In [12]:
u = p.numpy()
u

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
seed = 120
torch.manual_seed(seed)
g = torch.rand(3,4)
torch.manual_seed(seed)
h = torch.rand(3,4)
g == h

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [14]:
device = torch.device(dev) 
a = torch.zeros(4,3) 
a = a.to(device)

NameError: name 'dev' is not defined

In [15]:
machine = torch.device(dev) 
a = torch.zeros(4,3) 
a = a.to(device)

NameError: name 'dev' is not defined

In [ ]:
dev

'cuda:0'

In [16]:
if torch.cuda.is_available(): 
    mac = "cuda:0" 
else: 
    mac = "cpu" 
device = torch.device('cuda:0') 
a = torch.zeros(4,3) 
a = a.to(device)

In [17]:
torch.cuda.is_available()

True

In [18]:
torch.cuda.device_count()

1

In [ ]:
r = torch.arange(1000)

In [ ]:
h = r.to(mac)